name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - name: Update version
        run: |
          npm version ${{ github.event.release.tag_name }} --no-git-tag-version
          sed -i "s/\"version\": \".*\"/\"version\": \"${{ github.event.release.tag_name }}\"/" custom_components/sip_core/manifest.json
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Bump version to ${{ github.event.release.tag_name }}'
          push: origin HEAD:main
      - name: Build the file
        run: |
          npm ci
          npm run build
      - name: Create release zip
        run: |
          cd ${{ github.workspace }}/custom_components/sip_core
          zip sip_core.zip -r ./
      - name: Upload files to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/custom_components/sip_core/sip_core.zip
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
